kubernetes apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-app-backend
spec:
  selector:
    matchLabels:
      app: yolo-app-backend
  template:
    metadata:
      labels:
        app: yolo-app-backend
    spec:
      containers:
      - name: yolo-app-backend
        image: kipten/yolo-app-backend:v1.0.1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: yolo-app-backend-port
          containerPort: 5000
