#SPDX-License-Identifier: MIT-0
---
# tasks file for yolo_backend
- name: Run backend container
  docker_container:
    name: "{{ container_name }}"
    image: "{{ image }}"
    state: started
    restart_policy: always
    networks:
      - name: "{{ docker_network_name }}"
    ports:
      - "{{ port }}:{{ port }}"
  tags:
   - backend