#SPDX-License-Identifier: MIT-0
---
# tasks file for clone_repo

- name: Clone YOLO app repository
  git:
    repo: "{{ repo_url }}"
    dest: "{{ repo_dest }}"
    version: "{{ repo_branch }}"
    update: yes
